# 
control_dt: 0.02        # 50Hz
communication_dt: 0.002 # 500Hz

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "./models/Dec16_09-19-17_gym_dreamwaq_policy.pt"

leg_joint2motor_idx: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8] # align with joint sequence in IsaacGym
stand_kp: 60.0
stand_kd: 5.0
ctrl_kp: 20.0
ctrl_kd: 0.5
default_angles: [0.,  0.8,  -1.5,  0., 0.8, -1.5, 
                  0.0,  0.8,  -1.5,  0., 0.8, -1.5]
sit_angles: [0.04, 1.3, -2.87, -0.02, 1.29, -2.86,
          -0.33, 1.27, -2.81, 0.32, 1.28, -2.87]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [1.0, 1.0, 0.25]
num_actions: 12
num_single_obs: 45
frame_stack: 20

max_cmd: [1.0, 1.0, 1.]
